project_id = "vwezujtftfccamoduglp"

[functions.sync-nfl-games]
verify_jwt = false

[functions.sync-nba-odds]
verify_jwt = false

[functions.sync-nba-games]
verify_jwt = false

[functions.sync-ncaab-games]
verify_jwt = false

[functions.sync-ncaaf-games]
verify_jwt = false

[functions.sync-mlb-games]
verify_jwt = false

[functions.sync-odds-snapshot]
verify_jwt = false

[functions.sync-player-props]
verify_jwt = false

[functions.balldontlie]
verify_jwt = false

[functions.sync-nfl-players]
verify_jwt = false

[functions.sync-nfl-season-stats]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.sync-nba-players]
verify_jwt = false

[functions.sync-nfl-players-slate]
verify_jwt = false

[functions.sync-ncaab-players]
verify_jwt = false

[functions.search-nfl-players]
verify_jwt = false

[functions.nfl-slate-leaders]
verify_jwt = false

[functions.sportradar]
verify_jwt = false

[functions.analyst-query]
verify_jwt = false
