project_id = "pgrrbkhxukxvzzauviyp"

[functions.sync-nfl-games]
verify_jwt = false

[functions.sync-nfl-odds]
verify_jwt = false

[functions.sync-nba-odds]
verify_jwt = false

[functions.balldontlie]
verify_jwt = false
