// Full NFL team name -> abbreviation, matching src/utils/teamAbbreviations.ts
// conventions, plus historical names so the 2018+ backtest backfill resolves
// (Oakland through 2019, all three Washington names). Pure data, safe to
// import from vitest and from any edge function.

export const NFL_TEAM_ABBR: Record<string, string> = {
  "Arizona Cardinals": "ARI",
  "Atlanta Falcons": "ATL",
  "Baltimore Ravens": "BAL",
  "Buffalo Bills": "BUF",
  "Carolina Panthers": "CAR",
  "Chicago Bears": "CHI",
  "Cincinnati Bengals": "CIN",
  "Cleveland Browns": "CLE",
  "Dallas Cowboys": "DAL",
  "Denver Broncos": "DEN",
  "Detroit Lions": "DET",
  "Green Bay Packers": "GB",
  "Houston Texans": "HOU",
  "Indianapolis Colts": "IND",
  "Jacksonville Jaguars": "JAX",
  "Kansas City Chiefs": "KC",
  "Las Vegas Raiders": "LV",
  "Oakland Raiders": "LV",
  "Los Angeles Chargers": "LAC",
  "LA Chargers": "LAC",
  "San Diego Chargers": "LAC",
  "Los Angeles Rams": "LAR",
  "LA Rams": "LAR",
  "St. Louis Rams": "LAR",
  "Miami Dolphins": "MIA",
  "Minnesota Vikings": "MIN",
  "New England Patriots": "NE",
  "New Orleans Saints": "NO",
  "New York Giants": "NYG",
  "New York Jets": "NYJ",
  "Philadelphia Eagles": "PHI",
  "Pittsburgh Steelers": "PIT",
  "San Francisco 49ers": "SF",
  "Seattle Seahawks": "SEA",
  "Tampa Bay Buccaneers": "TB",
  "Tennessee Titans": "TEN",
  "Washington Commanders": "WAS",
  "Washington Football Team": "WAS",
  "Washington Redskins": "WAS",
};
